name: Pipeline

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  ruff:
    name: Ruff Linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install UV
        uses: astral-sh/setup-uv@v4
      - name: Set up Python
        run: uv python install
      - name: Install the project
        run: uv sync --dev
      - name: Ruff (linting + formating)
        id: ruff
        run: |
          uv run pre-commit run --all
      - name: Generate Badges
        if: success() || failure()
        run: |
          mkdir -p badges/
          uv run anybadge --overwrite --label=python --value="$(cat .python-version)" --value-format='%.2f' --file=badges/python.svg --color='dodgerblue'
          uv run anybadge --overwrite --value="${{ steps.ruff.outcome }}" --label=ruff --file=badges/ruff.svg success=green failure=red
          uv run anybadge --overwrite --label=version --value="v$(uvx --from=toml-cli toml get --toml-path=pyproject.toml project.version)" --file=badges/version.svg --color='green'
      - name: Publish badges to GitHub Pages
        if: (success() || failure()) && (github.ref_name == github.event.repository.default_branch)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: badges/
          clean: false

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: [ ruff ]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    environment:
      name: pypi
      url: https://pypi.org/p/gh-semantic-release
    permissions:
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install UV
        uses: astral-sh/setup-uv@v4
      - name: Set up Python
        run: uv python install
      - name: Install the project
        run: uv sync --dev
      - name: Build Project
        run: |
          uv build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
